### ISSUE TITLE
Build appears to be broken

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#108]
`make dist` fails with:

```
...
perl ../bin/cppwrap.pl marpa.h.p80 < ../dev/marpa.h.p80 > marpa.h.p80
cat ../shared/license.c ../shared/do_not_edit.c marpa.h.p10 marpa.h-err marpa.h-event marpa.h-step marpa.h.p50 marpa.h.p80 marpa.h.p90 > marpa.h
(cat ../shared/license.c ../shared/do_not_edit.c ; \
		for f in marpa_codes.c.p10 marpa.c-err marpa.c-event marpa.c-step; \
		do perl ../bin/cppwrap.pl $f < $f; \
		done) > marpa_codes.c
Cannot copy ac_doc/configure.ac -> doc/configure.ac at ../etc/copier.pl line 57, <STDIN> line 1.
make[1]: *** [timestamp/doc_build.stamp] Error 2
make: *** [timestamp/stage.stamp] Error 2
```
[Full log](https://github.com/jeffreykegler/libmarpa/files/8722386/LOG.txt)

**Comment by dabrahams** [comment]
git bisect identifies faeb10f1dc30 as the place where this problem was introduced.

**Comment by jeffreykegler** [comment]
There are lots of complicated multiple dependencies in the build which don't work well, and I usually find it necessary to run a "make clean" first.

Btw, the head of my main branch is not always something buildable.  I know that is a practice some folks take pride in, but I need the cloud for backup, and often push something broken.  Unless I point out a commit as useful, you're rolling the dice if you build from it.

"make clean; make dist" works, and "make test" tests all ok, as of the current commit: fe0174fe9be5c8d4c27f7d8e13c5bbce0c4d7419.

**Comment by jeffreykegler** [comment]
The issue about errors, #79, has prompted a near-total rewrite of the API doc, which in turn has suggested some changes to the CWeb and the code.  These, in their turn, have prompted me to create a smoother flow for testing via Marpa::R2, which is what i am doing at the moment.

**Comment by dabrahams** [comment]
Of course I ran "make clean" first.

> "make clean; make dist" works, and "make test" tests all ok, as of the current commit: https://github.com/jeffreykegler/libmarpa/commit/fe0174fe9be5c8d4c27f7d8e13c5bbce0c4d7419.

>Btw, the head of my main branch is not always something buildable. I know that is a practice some folks take pride in, but I need the cloud for backup, and often push something broken. Unless I point out a commit as useful, you're rolling the dice if you build from it.

I don't care whether it's your “main” branch, but it's a good idea to maintain _a_ branch that's always in a buildable state, so that bisect can work and so that CI can be useful, among other things.

> "make clean; make dist" works, and "make test" tests all ok, as of the current commit: https://github.com/jeffreykegler/libmarpa/commit/fe0174fe9be5c8d4c27f7d8e13c5bbce0c4d7419.

Not for me.

```
$ make clean; make dist
...
cat ../shared/do_not_edit.c >> marpa.h
perl -ne \
	'exit if m/^[\/][*] === VERSION NUMBERS GO HERE /; \
	 print if $flag; \
	  { $flag=1 } if m/^[\/][*] === DO NOT CHANGE ME /;' \
	    marpa.h.raw >>marpa.h
syntax error at -e line 1, near "if m/^[\/][*] === DO NOT CHANGE ME /"
Execution of -e aborted due to compilation errors.
make[2]: *** [marpa.h] Error 255
```

**Comment by jeffreykegler** [comment]
Following your suggestion, I'll create a branch called "tested".  That won't happen until I make some changes.  I am going to try to make the Makefile more portable, perhaps converting the perl (which I hope would be widely available and standard, but has no POSIX spec) to sed and/or awk.

**Comment by jeffreykegler** [comment]
I've converted the problematic logic to `sed`, and pushed a new "tested" branch, whose head contains the fix.

**Comment by jeffreykegler** [comment]
Oops!  Please ignore comment https://github.com/jeffreykegler/libmarpa/issues/108#issuecomment-1131964805.  Just as a check, I cloned the repo, tried a 'make dist' in the new repo, and it failed with the error reported in https://github.com/jeffreykegler/libmarpa/issues/108#issue-1240933615.  So I need to fix this.

**Comment by jeffreykegler** [comment]
The problem of https://github.com/jeffreykegler/libmarpa/issues/108#issuecomment-1131975769 is fixed (I hope!) in d58c05e1f1e5bd7e9b1c379702c0a665ad47a139 which is the current head of the "tested" branch.

**Comment by dabrahams** [comment]
"make dist" still fails for me on a clean repo as shown

[make-dist.txt](https://github.com/jeffreykegler/libmarpa/files/8747832/make-dist.txt)

**Comment by jeffreykegler** [comment]
I just did exactly that test on the head of the "tested" branch about 5 minutes ago, and it was OK on my setup.

Lots of complaints about the api.texi file. Could you send me a copy?

Thanks, jeffrey

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by jeffreykegler** [comment]
Perhaps this is still a problem with the portability of Perl one-liners: https://github.com/jeffreykegler/libmarpa/issues/110#issuecomment-1133662078.

**Comment by dabrahams** [comment]
Here's the api.texi file: [api.texi.txt](https://github.com/jeffreykegler/libmarpa/files/8748264/api.texi.txt)

**Comment by dabrahams** [comment]
This problem is because on a Mac, `makeinfo` is texinfo 4.8, even if you've installed `texinfo` with homebrew, unless you've done something to ensure homebrew's texinfo is first in your PATH.  I'll try to adjust the brew formula accordingly and see what happens.

**Comment by jeffreykegler** [comment]
I've made more fixes in the current head of the "tested" branch: 30a3ea8f3b41e14408cef11d4aa8efe818633b96. All Perl "oneliners" are now eliminated, usuallly in favor of `sed`. Perhaps these changes offer some improvement.

**Comment by dabrahams** [comment]
Once I required brew's `texinfo` as a build dependency, the brew formula started working.  Retesting with head of "tested"… seems to work.

**Comment by jeffreykegler** [comment]
Per [the last comment](https://github.com/jeffreykegler/libmarpa/issues/108#issuecomment-1135256052), and absent feedback to the contrary, I will close this issue in a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/libmarpa/issues/108#issuecomment-1135997005.
